import { GoogleOAuthProvider } from '@react-oauth/google'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import type { PropsWithChildren } from 'react'

import { CookieConsent } from '@/components/cookie-consent'
import { Footer } from '@/components/footer'
import { Header } from '@/components/header'
import { ReactQueryProvider } from '@/providers/react-query-provider'
import './globals.css'

const montserrat = Montserrat({
    subsets: ['cyrillic'],
    weight: ['400', '500', '600', '700'],
    display: 'block',
    preload: true
})

export const metadata: Metadata = {
    title: 'Amster',
    description: 'Generated by create next app'
}

const clientId =
    '586948538433-m3kq8a79oogn5dbksh08dfth5s1462ej.apps.googleusercontent.com'

const RootLayout = ({ children }: PropsWithChildren) => {

    return (
        <html lang='en'>
            <body className={`${montserrat.className} antialiased`}>
                <GoogleOAuthProvider clientId={clientId}>
                    <ReactQueryProvider>
                        <Header />

                        <main>
                            <NuqsAdapter>{children}</NuqsAdapter>
                        </main>

                        <Footer />
                        <CookieConsent />
                    </ReactQueryProvider>
                </GoogleOAuthProvider>
            </body>
        </html>
    )
}
export default RootLayout
