import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import type { PropsWithChildren } from 'react'

import './globals.css'
import { Header } from '@/components/header'

const montserrat = Montserrat({
    subsets: ['cyrillic'],
    weight: ['400', '500', '600', '700'],
    display: 'block',
    preload: true
})

export const metadata: Metadata = {
    title: 'Amster',
    description: 'Generated by create next app'
}

const RootLayout = ({ children }: PropsWithChildren) => {
    return (
        <html lang='en'>
            <body className={`${montserrat.className} antialiased`}>
                <Header />
                {children}
            </body>
        </html>
    )
}

export default RootLayout
