services:

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/backend/static
      - ./nginx/development:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
      - frontend

  redis:
    image: redis
  celery:
    image: flora_latest
    volumes:
      - ./backend:/app/backend
    command: celery -A amster_flora worker --beat --loglevel=info
    env_file:
      - ./backend/.env
    depends_on:
      - backend
      - redis

  backend:
    restart: unless-stopped
    image: flora_latest
    build: ./backend
    entrypoint: /app/backend/entrypoint.sh
    volumes:
      - static_volume:/app/backend/static
      - ./backend:/app/backend/
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
      # One-way volume to use node_modules from inside image
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./frontend/.env
    command: npm run start:server

volumes:
  static_volume: