# Generated by Django 5.1.3 on 2024-11-28 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_crm', '0001_initial'),
        ('products', '0003_alter_variant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='key_crm_id',
        ),
        migrations.RemoveField(
            model_name='component',
            name='origin_sku',
        ),
        migrations.AddField(
            model_name='component',
            name='key_crm_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='key_crm.keycrmproduct'),
        ),
    ]
