# Generated by Django 5.1.4 on 2025-04-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_component_key_crm_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='quantity_sold',
        ),
    ]
