# Generated by Django 5.1.4 on 2025-04-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('liqpay', 'Liqpay'), ('wayforpay', 'Wayforpay')], default='liqpay', max_length=55),
        ),
    ]
