# Generated by Django 5.1.3 on 2024-11-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycrmproduct',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='keycrmproduct',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='keycrmproduct',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='keycrmproduct',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='keycrmproduct',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
