# Generated by Django 5.1.4 on 2025-04-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_crm', '0002_alter_keycrmproduct_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycrmproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='keycrmproduct',
            name='purchased_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
