import { GoogleOAuthProvider } from '@react-oauth/google'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import type { PropsWithChildren } from 'react'

import '../globals.css'

import { AdminSidebar } from './admin-sidebar'
import { CookieConsent } from '@/components/cookie-consent'
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import { ReactQueryProvider } from '@/providers/react-query-provider'

const montserrat = Montserrat({
    subsets: ['cyrillic'],
    weight: ['400', '500', '600', '700'],
    display: 'block',
    preload: true
})

export const metadata: Metadata = {
    title: 'Amster',
    description: 'Generated by create next app'
}

const clientId =
    '586948538433-m3kq8a79oogn5dbksh08dfth5s1462ej.apps.googleusercontent.com'

const RootLayout = ({ children }: PropsWithChildren) => {
    return (
        <html lang='en'>
            <body
                className={`${montserrat.className} flex min-h-screen flex-col antialiased`}>
                <GoogleOAuthProvider clientId={clientId}>
                    <ReactQueryProvider>
                        <SidebarProvider>
                            <AdminSidebar />
                            <main className='container flex-grow pt-2'>
                                <SidebarTrigger />
                                <NuqsAdapter>{children}</NuqsAdapter>
                            </main>
                        </SidebarProvider>

                        <CookieConsent />
                    </ReactQueryProvider>
                </GoogleOAuthProvider>
            </body>
        </html>
    )
}
export default RootLayout
