name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GITHUB_WORKSPACE
        run: echo "$GITHUB_WORKSPACE"
      - name: Create backend .env
        uses: DeveloperRic/action-create-env@v1.0.2
        with:
          full_text: |
            ENVIRONMENT=local
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            DEBUG=${{ secrets.DEBUG }}
            DB_NAME=postgres
            DB_USER=postgres
            DB_HOST=db
            DB_PASSWORD=postgres
            DB_PORT=5432
            EMAIL_USER=${{ secrets.EMAIL_USER }}
            EMAIL_HOST=${{ secrets.EMAIL_HOST }}
            EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
            EMAIL_PORT=${{ secrets.EMAIL_PORT }}
          directory: ${{ github.workspace }}/backend
      - name: Create frontend .env
        uses: DeveloperRic/action-create-env@v1.0.2
        with:
          full_text: |
            GOOGLE_AUTH_CLIENT_ID=${{ secrets.GOOGLE_AUTH_CLIENT_SECRET }}
            FACEBOOK_APP_ID=${{ secrets.FACEBOOK_APP_ID }}
          directory: ${{ github.workspace }}/frontend
      - name: Build the Docker image
        run: docker logout && docker compose up --build -d
      - name: run Tests
        run: docker compose run --rm backend sh -c "python3 ./manage.py test"
      - name: Stop containers
        if: always()
        run: docker compose down