name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: GITHUB_WORKSPACE
        run: echo "$GITHUB_WORKSPACE"
      - name: Create .env
        uses: DeveloperRic/action-create-env@v1.0.2
        with:
          full_text: |
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            DEBUG=${{ secrets.DEBUG }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_PORT=${{ secrets.DB_PORT }}
            EMAIL_USER=${{ secrets.EMAIL_USER }}
            EMAIL_HOST=${{ secrets.EMAIL_HOST }}
            EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
            EMAIL_PORT=${{ secrets.EMAIL_PORT }}
          directory: ${{ github.workspace }}/backend
      - name: Stop containers
        run: docker compose stop
      - name: Build the Docker image
        run: docker compose -f docker-compose-prod.yaml build
      - name: Run containers
        run: docker compose -f docker-compose-prod.yaml up -d
      - name: Run exist containers
        if: ${{ failure() }}
        run: docker compose -f docker-compose-prod.yaml up -d
      - name: Remove not used images and volumes (clean up file system in AWS)
        if: ${{ success() }}
        run: docker system prune -f -a --volumes
