name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4.2.2
      - name: GITHUB_WORKSPACE
        run: echo "$GITHUB_WORKSPACE"
      - name: Create backend .env
        uses: DeveloperRic/action-create-env@v1.0.2
        with:
          full_text: |
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            DEBUG=${{ secrets.DEBUG }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_PORT=${{ secrets.DB_PORT }}
            EMAIL_USER=${{ secrets.EMAIL_USER }}
            EMAIL_HOST=${{ secrets.EMAIL_HOST }}
            EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
            EMAIL_PORT=${{ secrets.EMAIL_PORT }}
            AWS_S3_ACCESS_KEY_ID=${{ secrets.AWS_S3_ACCESS_KEY_ID }}
            AWS_S3_SECRET_ACCESS_KEY=${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
            AWS_STORAGE_BUCKET_NAME=${{ secrets.AWS_STORAGE_BUCKET_NAME }}
            GOOGLE_AUTH_CLIENT_ID=${{ secrets.GOOGLE_AUTH_CLIENT_ID }}
            GOOGLE_AUTH_CLIENT_SECRET=${{ secrets.GOOGLE_AUTH_CLIENT_SECRET }}
            FACEBOOK_APP_ID=${{ secrets.FACEBOOK_APP_ID }}
            FACEBOOK_APP_SECRET=${{ secrets.FACEBOOK_APP_SECRET }}
            REDIS_URL=${{ secrets.REDIS_URL }}
            BROKER_URL=${{ secrets.BROKER_URL }}
            KEY_CRM_API_KEY=${{ secrets.KEY_CRM_API_KEY }}
            LIQPAY_PUBLIC_KEY=${{ secrets.LIQPAY_PUBLIC_KEY }}
            LIQPAY_PRIVATE_KEY=${{ secrets.LIQPAY_PRIVATE_KEY }}
            WAYFORPAY_MERCHANT_LOGIN=${{ secrets.WAYFORPAY_MERCHANT_LOGIN }}
            WAYFORPAY_SECRET_KEY=${{ secrets.WAYFORPAY_SECRET_KEY }}
          directory: ${{ github.workspace }}/backend
      - name: Create frontend .env
        uses: DeveloperRic/action-create-env@v1.0.2
        with:
          full_text: |
            GOOGLE_AUTH_CLIENT_ID=${{ secrets.GOOGLE_AUTH_CLIENT_ID }}
            FACEBOOK_APP_ID=${{ secrets.FACEBOOK_APP_ID }}
          directory: ${{ github.workspace }}/frontend
      - name: Stop containers
        run: docker compose stop
      - name: Remove containers
        run: docker compose -f docker-compose-prod.yaml down
      - name: Build the Docker image
        run: docker compose -f docker-compose-prod.yaml build
      - name: Run containers
        run: docker compose -f docker-compose-prod.yaml up -d
      - name: Run exist containers
        if: ${{ failure() }}
        run: docker compose -f docker-compose-prod.yaml up -d
      - name: Remove not used images and volumes (clean up file system in AWS)
        if: ${{ success() }}
        run: docker system prune -f -a --volumes
