name: Docker Image CI

on:
  push:
    branches: [ "production" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: GITHUB_WORKSPACE
        run: echo "$GITHUB_WORKSPACE"
      - name: Create .env
        uses: DeveloperRic/action-create-env@v1.0.2
        with:
          full_text: |
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            DEBUG=${{ secrets.DEBUG }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_PORT=${{ secrets.DB_PORT }}
            EMAIL_USER=${{ secrets.EMAIL_USER }}
            EMAIL_HOST=${{ secrets.EMAIL_HOST }}
            EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
            EMAIL_PORT=${{ secrets.EMAIL_PORT }}
            FE_URL=${{ secrets.FE_URL }}
            AWS_S3_ACCESS_KEY_ID=${{ secrets.AWS_S3_ACCESS_KEY_ID }}
            AWS_S3_SECRET_ACCESS_KEY=${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
            AWS_STORAGE_BUCKET_NAME=${{ secrets.AWS_STORAGE_BUCKET_NAME }}
            ACCESS_TOKEN_LIFETIME=${{ secrets.ACCESS_TOKEN_LIFETIME }}
            TOKEN_1C_CONNECTION=${{ secrets.TOKEN_1C_CONNECTION }}
            TOKEN_TELEGRAM_CONNECTION=${{ secrets.TOKEN_TELEGRAM_CONNECTION }}
            GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
            KEY_CRM_API_KEY=${{ secrets.KEY_CRM_API_KEY }}
            GOOGLE_SHEET_PRICE_URL=${{ secrets.GOOGLE_SHEET_PRICE_URL }}
          directory: ${{ github.workspace }}/backend
      - name: Create google_key.json
        uses: jsdaniell/create-json@v1.2.3
        id: create-json
        with:
          name: google_key.json
          json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          dir: backend/
      - name: Stop containers
        run: docker compose stop
      - name: Build the Docker image
        run: docker compose -f docker-compose-prod.yaml build
      - name: Run containers
        run: docker compose -f docker-compose-prod.yaml up -d
      - name: Run exist containers
        if: ${{ failure() }}
        run: docker compose -f docker-compose-prod.yaml up -d
      - name: Remove not used images and volumes (clean up file system in AWS)
        if: ${{ success() }}
        run: docker system prune -f -a --volumes
